version: '3.9'
services:
  rest-soft-walter:
    image: walter/rest-with-spring-boot-soft-walter
    restart: always
    build: .
#      context: "../local"
#      dockerfile: Dockerfile
    working_dir: /rest-with-spring-boot-soft-walter
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc://localhost:3308/bd?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:80
    command: mvn spring-boot:run
#    depends_on:
#      - db
    networks:
      - walter-network
  #  db:
  #    image: mysql:8.0
  #    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
  #    # (this is just an example, not intended to be a production configuration)
  #    command: --default-authentication-plugin=mysql_native_password
  #    restart: always
  #    environment:
  #      TZ: America/Sao_Paulo
  #      MYSQL_ROOT_PASSWORD: admin123
  #      MYSQL_USER: docker
  #      MYSQL_PASSWORD: admin123
  #      MYSQL_ROOT_HOST: '%'
  #      MYSQL_TCP_PORT: 3308
  #    ports:
  #      - "3308:3308"
  #    expose:
  #      - 3808
  #    networks:
  #      - walter-network
networks:
  walter-network:
    driver: bridge

















